### PR TITLE
Casc compatibility using PersistedList

### PR DESCRIPTION
**Pull request by martinda**
Adding Configuration as Code compatibility on top of an up to date pom, using the `PersistedList` approach used in PR #52 by @ndeloof 

Summary of this pull request:
- Use `PersistedList` data type
- Ensure getter remains in place

@ndeloof can you help please? This fails mvn test with the following in the stack trace:
```
[ERROR] fallbackToGlobalAllocationStrategy(org.jenkinsci.plugins.ewm.steps.DiskAllocationStrategyTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalArgumentException: Can not set final hudson.util.PersistedList field org.jenkinsci.plugins.ewm.steps.ExwsAllocateStep$DescriptorImpl.diskPools to java.util.Collections$EmptyList
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
        at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:83)
        at java.lang.reflect.Field.set(Field.java:764)
        at org.springframework.util.ReflectionUtils.setField(ReflectionUtils.java:96)
        at org.jenkinsci.plugins.ewm.TestUtil.setUpDiskPools(TestUtil.java:60)
        at org.jenkinsci.plugins.ewm.TestUtil.removeDiskPools(TestUtil.java:52)
        at org.jenkinsci.plugins.ewm.steps.DiskAllocationStrategyTest.tearDown(DiskAllocationStrategyTest.java:38)
        at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:421)
        at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:386)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:548)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)
```

CC @ewelinawilkosz @oleg-nenashev

### CODE REVIEW

**Comment by martinda** [comment]
The error happens in this call:
https://github.com/jenkinsci/external-workspace-manager-plugin/blob/08073fc5c2878633f5129b6d583b83c5263274a7/src/test/java/org/jenkinsci/plugins/ewm/TestUtil.java#L58

**Comment by alexsomai** [comment]
@martinda I think that there may be two cases:

1. Maybe the issue comes from the method that calls it.
Probably if you replace https://github.com/jenkinsci/external-workspace-manager-plugin/blob/08073fc5c2878633f5129b6d583b83c5263274a7/src/test/java/org/jenkinsci/plugins/ewm/TestUtil.java#L52 by

```java
setUpDiskPools(jenkins, new PersistedList<DiskPool>());
```

2. Maybe is because the field is set to `final`. In this case, using Reflection, you'll have to remove the `final` modifier.

From this example https://stackoverflow.com/questions/2474017/using-reflection-to-change-static-final-file-separatorchar-for-unit-testing, this is how you could do it:

```java
// remove final modifier from field
Field modifiersField = Field.class.getDeclaredField("modifiers");
modifiersField.setAccessible(true);
modifiersField.setInt(diskPoolsField, diskPoolsField.getModifiers() & ~Modifier.FINAL);
```

**Comment by ndeloof** [comment]
you should fully reimplement setUpDiskPools to rely on `PersistentList.replaceBy`. It makes perfect sense diskPool is public final

**Comment by martinda** [comment]
@ndeloof sorry but I am completely clueless. I tried this, but obviously it fails since PersistedList.replaceBy is not static. I do not even know if I should still use RelfectionUtils or something else, and since you said "fully reimplement" I imagine the whole method is completely wrong now.

```java
   private static void setUpDiskPools(Jenkins jenkins, List<DiskPool> diskPools) {
        ExwsAllocateStep.DescriptorImpl descriptor = (ExwsAllocateStep.DescriptorImpl) jenkins.getDescriptor(ExwsAllocateStep.class);

        Field diskPoolsField = ReflectionUtils.findField(ExwsAllocateStep.DescriptorImpl.class, "diskPools");
        diskPoolsField.setAccessible(true);
        ReflectionUtils.invokeMethod(PersistedList.replaceBy, diskPoolsField, diskPools);
    }
```

**Comment by ndeloof** [comment]
For casc you need to expose diskpools field, either by making it a public PersistedList or by offering a setter to replace list content. In both cases you don't need reflection anymore in this test helper method.
Either descriptor.diskpools.replaceall(values)
Or
descriptor.setDiskpools(values)

**Comment by martinda** [comment]
I marked the branch as do not merge because even though it passes the tests, it is still missing casc tests.

**Comment by martinda** [comment]
I have a new problem with PersistedList.

1) I load the external workspace manager plugin in a live Jenkins instance
2) I configure it
3) Save the configuration

An exception is thrown about the PersistedList. It says there is a protected member.

```
java.lang.IllegalAccessException: Class org.jvnet.tiger_types.Lister can not access a member of class hudson.util.PersistedList with modifiers "protected"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.Class.newInstance(Class.java:436)
	at org.jvnet.tiger_types.Lister.create(Lister.java:124)
Caused: java.lang.IllegalAccessError
	at org.jvnet.tiger_types.Lister.toError(Lister.java:160)
	at org.jvnet.tiger_types.Lister.create(Lister.java:146)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:642)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:489)
	at org.jenkinsci.plugins.ewm.steps.ExwsAllocateStep$DescriptorImpl.configure(ExwsAllocateStep.java:105)
	at jenkins.model.Jenkins.configureDescriptor(Jenkins.java:3731)
	at jenkins.model.Jenkins.doConfigSubmit(Jenkins.java:3695)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
```

Once more, can someone help?

**Comment by martinda** [comment]
To be noticed: the current test checks the job-restriction plugin configuration since it is possible for the user to use it as part of this plugin.

@oleg-nenashev I am thinking that the [job-restriction](https://github.com/jenkinsci/job-restrictions-plugin) plugin should have its own CasC test, since it is used by this plugin. What do you think? And also, any advice on how to test CasC in the job-restriction plugin? Looks like to test CasC in the job-restriction plugin, a job with all the possible restrictions should be programmatically created, but CasC is not for configuring jobs, so I am not sure how to proceed here.

**Comment by ndeloof** [comment]
I'm very disappointed I just discover stapler's bindJson(object,json) do **not** support `PersistedList.replaceBy` and so you'll need to expose a setter to invoke it by yourself. Something to be considered for https://github.com/stapler/stapler/pull/147 as I found this to be very frustrating ;)

**Comment by martinda** [comment]
This is replaced by #68 . Closing.

**Pull request closed without merging**
