### PR TITLE
Use FileDynamicPathContext for compatibility with Jenkins 2.150.x+

### PR DESCRIPTION
**Pull request by martinda**
This fixes the issue reported in the [mailing list](https://groups.google.com/forum/#!topic/jenkinsci-dev/TXBLRt5ZxjI), related to the change made in Jenkins 2.150.x where workspaces need to be wrapped in `FileDynamicPathContext` (see [this example](https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/101/files#diff-08a6dd4e3141d4c4e0c00e1e80734e19)).

Summary of this pull request:
- [x] Upgrade the pom to use the BOM
- [x] Provide unit test
- [x] Provide fix by using [FileDynamicPathContext](src/main/java/org/jenkinsci/plugins/workflow/support/steps/FilePathDynamicContext.java)

CC @oleg-nenashev @alexsomai

### CODE REVIEW

**Comment by martinda** [comment]
Note that I have an issue locally with flaky tests. I posted [a question to the dev mailing list](https://groups.google.com/forum/#!topic/jenkinsci-dev/EKvDiKCz96c).

**Comment by martinda** [comment]
The build actually passed, but Github was not updated. Closing and re-opening to trigger a new build.

**Comment by martinda** [comment]
Well, that was a waste, the build did not re-trigger.

**Comment by martinda** [comment]
@alexsomai I am ready to merge and release this at your convenience.

**Comment by alexsomai** [comment]
@martinda Merging this and I'll perform a release right after.

**Pull request merged**
